### ISSUE TITLE
Use without eth1 Node or with infura WS endpoint

### ISSUE THREAD

**Issue by davidkassa** [jshear-crypto/rocketpool-beta-dashboard#3]
I'd like to try this out without setting up a geth instance on my test node. Can this be used somehow with Infura (or omitted for eth1)?

**Comment by jshear** [comment]
When I was testing it a while ago I kept getting an error message from Infura for exceeding the allowed request rate. I can update it to allow an Infura address instead of a host/port, and you can play around with Infura configs to see if you can get it to work. Not sure how many requests it'll send every time you fetch the leaderboard (it needs an individual request to get the information for each minipool on the Rocket Pool network, so probably a couple hundred).

The Infura address you'll use will be the address without the protocol. So if the address is `wss://infura.io/something`, just put `infura.io/something`

Unfortunately Eth1 can't be omitted since it's needed for getting the minipools in the network. Hopefully you can get Infura to work though.

**Comment by jshear** [comment]
Done. The eth1 address should have the format `goerli.infura.io/ws/...`. If you have an error, it's almost definitely the Infura request rate being exceeded, but I haven't had any luck configuring Infura to get it to work (I also don't have any real experience with Infura, though). Let me know if you get it working, good luck
